### ISSUE TITLE
Is this LDAP ?

### ISSUE THREAD

**Issue by collegeimprovements** [dthree/addict#3]
Can we run some mock LDAP server with it?

I ran `addict --url ldaps://localhost --user dthree@localhost --pass dthree1234`

and it keep showing `addict:` on the command prompt. What should I enter there?

**Comment by dthree** [comment]
You can connect to an LDAP server. Addict isn't a server in itself. It is an LDAP client that exposes a REST API.

The reason I say Active Directory instead of LDAP is because some things (such as pagination) don't work out of the box with any LDAP server.

---

> and it keep showing addict: on the command prompt. What should I enter there?

You don't have to do anything on the prompt. That just shows you it's running. You would hit the rest api by browsing to `http://localhost/api`.
